// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotDefteriApi.Data;

#nullable disable

namespace NotDefteriApi.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20230202163824_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NotDefteriApi.Data.Not", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DegistirmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Notlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baslik = "Alinacaklar",
                            DegistirmeZamani = new DateTime(2023, 2, 2, 19, 38, 23, 955, DateTimeKind.Local).AddTicks(3394),
                            Icerik = "1. Bot\n2. Kot",
                            OlusturulmaZamani = new DateTime(2023, 2, 2, 19, 38, 23, 955, DateTimeKind.Local).AddTicks(3385)
                        },
                        new
                        {
                            Id = 2,
                            Baslik = "Gorevler",
                            DegistirmeZamani = new DateTime(2023, 2, 2, 19, 38, 23, 955, DateTimeKind.Local).AddTicks(3399),
                            Icerik = "1. Ye\n2. Dua et\n3. Sev",
                            OlusturulmaZamani = new DateTime(2023, 2, 2, 19, 38, 23, 955, DateTimeKind.Local).AddTicks(3398)
                        },
                        new
                        {
                            Id = 3,
                            Baslik = "Gez & Gör",
                            DegistirmeZamani = new DateTime(2023, 2, 2, 19, 38, 23, 955, DateTimeKind.Local).AddTicks(3401),
                            Icerik = "1. Muş\n2. Van\n3. Of",
                            OlusturulmaZamani = new DateTime(2023, 2, 2, 19, 38, 23, 955, DateTimeKind.Local).AddTicks(3400)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
